target-version = "py312"
line-length = 120

[lint]
# See rules at https://docs.astral.sh/ruff/rules/
extend-select = [
    "B",
    "D",
    "E",
    "F",
    "I",
    "N",
    "Q",
    "W",
    "C90",
    "ANN",
    "BLE",
    "ERA",
    "FA",
    "FLY",
    "ISC",
    "PL",
    "RET",
    "RUF",
    "SIM",
    "TRY",
    "UP",
    "YTT",
]
extend-ignore = ["ANN101", "ANN102", "D105", "D107", "D203", "D213", "TRY003"]
fixable = ["ALL"]

[lint.per-file-ignores]
"tests/*.py" = ["D", "ANN", "PLR2004"]
